// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhJvGbz8Yx5NwwFGOd73_3P6rRSt0eBM',
    appId: '1:453376594918:web:f53da1de1bfc151cffbc27',
    messagingSenderId: '453376594918',
    projectId: 'oceanoasis-2929d',
    authDomain: 'oceanoasis-2929d.firebaseapp.com',
    storageBucket: 'oceanoasis-2929d.appspot.com',
    measurementId: 'G-07TD0W2WEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeTNhyrhefxPY2QVwYh6rDgi4hQBE8Rb8',
    appId: '1:453376594918:android:44a19b0805bbb5f6ffbc27',
    messagingSenderId: '453376594918',
    projectId: 'oceanoasis-2929d',
    storageBucket: 'oceanoasis-2929d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0NKFJcd0GIV4QcC2E9VmT0qv9cBltZtM',
    appId: '1:453376594918:ios:259f778065b61503ffbc27',
    messagingSenderId: '453376594918',
    projectId: 'oceanoasis-2929d',
    storageBucket: 'oceanoasis-2929d.appspot.com',
    iosBundleId: 'net.pixelbrain.oceanoasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0NKFJcd0GIV4QcC2E9VmT0qv9cBltZtM',
    appId: '1:453376594918:ios:e8ddd528b8325307ffbc27',
    messagingSenderId: '453376594918',
    projectId: 'oceanoasis-2929d',
    storageBucket: 'oceanoasis-2929d.appspot.com',
    iosBundleId: 'net.pixelbrain.oceanoasis.RunnerTests',
  );
}
